In [445]:
import pandas as pd
data=[2,3,4,5,6,]
data

[2, 3, 4, 5, 6]

In [446]:
import pandas as pd

data = {
  'name': ["loki", "san", "mali"],
  'email':["loki@gmail.com","san2@gmail.com","mali420@gmail.com"],
  'salary':["100000","200000","300000"]
  }

data_table = pd.DataFrame(data)
print(data_table)


   name              email  salary
0  loki     loki@gmail.com  100000
1   san     san2@gmail.com  200000
2  mali  mali420@gmail.com  300000


In [447]:
data_table["age"]=[20,30,40]
data_table

name              email  salary  age
0  loki     loki@gmail.com  100000   20
1   san     san2@gmail.com  200000   30
2  mali  mali420@gmail.com  300000   40

In [448]:
data_table[data_table["age"]>30]


name              email  salary  age
2  mali  mali420@gmail.com  300000   40

In [449]:
data_table.describe()

age
count   3.0
mean   30.0
std    10.0
min    20.0
25%    25.0
50%    30.0
75%    35.0
max    40.0

In [450]:
#sample green technology projcet data(dataframe)
renewable_sources_sources=["solar","wind","hydrogen","geothermal","biomass"]
data={
    "project":["solar farm A","wind turbine X","Hydrogen Y","solar roof Z","geothermal plant P"],
    "Technology":["solar","wind","hydrogen","solar","geothermal"],
    "Capacity(MW)":[150,300,200,50,100],
    "Cost(Million $)":[200,400,350,100,250],
    "Location":["california","texas","washington","nevada","idaho"],
    "Completion Year":[2023,2024,2022,2025,2023]
}

In [451]:
projects_df=pd.DataFrame(data)
print("\nLoki Technology Projects,DataFrame")
print(projects_df)


Loki Technology Projects,DataFrame
              project  Technology  Capacity(MW)  Cost(Million $)    Location  \
0        solar farm A       solar           150              200  california   
1      wind turbine X        wind           300              400       texas   
2          Hydrogen Y    hydrogen           200              350  washington   
3        solar roof Z       solar            50              100      nevada   
4  geothermal plant P  geothermal           100              250       idaho   

   Completion Year  
0             2023  
1             2024  
2             2022  
3             2025  
4             2023  


In [452]:
projects_df["Cost per MW"]=projects_df["Cost(Million $)"]/projects_df["Capacity(MW)"]
print(projects_df)

              project  Technology  Capacity(MW)  Cost(Million $)    Location  \
0        solar farm A       solar           150              200  california   
1      wind turbine X        wind           300              400       texas   
2          Hydrogen Y    hydrogen           200              350  washington   
3        solar roof Z       solar            50              100      nevada   
4  geothermal plant P  geothermal           100              250       idaho   

   Completion Year  Cost per MW  
0             2023     1.333333  
1             2024     1.333333  
2             2022     1.750000  
3             2025     2.000000  
4             2023     2.500000  


In [453]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [454]:
print("this is 1d",np.zeros(5).astype(int))
print("this is 1d",np.ones(10))
print("this is 2d")
print(np.zeros((5,4)))
print(np.random.randint(0,10,5))

this is 1d [0 0 0 0 0]
this is 1d [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
this is 2d
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 9 7 0 9]
